### ISSUE TITLE
Hiển thị tin TÀI TRỢ trong danh sách tin ứng dụng Baomoi IOS

### ISSUE THREAD

**Issue by sonha79** [Ultimate-Hosts-Blacklist/hostsVN#2]
Mấy bừa nay ứng dụng Baomoi (iOS) xuất hiện tiêu đề tin tài trợ trong danh sách tin. Bấm vào thì không có nội dung (QC bị chặn).
iOS 13.5 (jailbreak từ lâu)
Ứng dụng Baomoi mới nhất từ AppStore.

![image](https://user-images.githubusercontent.com/2282128/94421088-409f0500-01af-11eb-891c-7cd1d91d3510.jpeg)

**Comment by sonha79** [comment]
![image](https://user-images.githubusercontent.com/2282128/94512741-fd907080-0246-11eb-8197-34f0d42640e1.png)
Đóng mở lại Baomoi thì vẫn hiện popup

**Comment by sonha79** [comment]
Xoá app cài lại thì vấn đề đã được giải quyết. 
Xin đóng lại vấn đề.

**Comment by funilrys** [comment]
Can you translate in English @sonha79 ? 

Please report any issue at https://github.com/Ultimate-Hosts-Blacklist/hostsVN/blob/fec2462a0b20d0b898cc3e0d33f190e9a614717f/info.json#L20

Stay safe and healthy.
Nissar
